const log_out = document.getElementsByClassName("log-out")[0];
const log_out_modal = document.getElementById("logout-modal");
const cancel_logout_button = document.getElementById("cancel-logout");
const confirm_logout_button = document.getElementById("confirm-logout");
const player_button = document.getElementsByClassName("player")[0];
const dm_button = document.getElementsByClassName("DM")[0];
const logo = document.getElementsByClassName("logo")[0];
const button_container = document.getElementsByClassName("buttons-placeholder")[0];

const campaigns1 = [
    {
        "campaign_name": "test1", "status": "player", "character_name": "Steve Rogers"
    },
    {
        "campaign_name": "test2", "status": "DM", "amout_of_players": "5"
    },
    {
        "campaign_name": "test3", "status": "player", "character_name": "Crash Bandicot"
    },
    {
        "campaign_name": "test1", "status": "player", "character_name": "Steve Rogers"
    },
    {
        "campaign_name": "test2", "status": "DM", "amout_of_players": "5"
    },
    {
        "campaign_name": "test3", "status": "player", "character_name": "Crash Bandicot"
    },
    {
        "campaign_name": "test1", "status": "player", "character_name": "Steve Rogers"
    },
    {
        "campaign_name": "test2", "status": "DM", "amout_of_players": "5"
    },
    {
        "campaign_name": "test3", "status": "player", "character_name": "Crash Bandicot"
    },
    {
        "campaign_name": "test1", "status": "player", "character_name": "Steve Rogers"
    },
    {
        "campaign_name": "test2", "status": "DM", "amout_of_players": "5"
    },
    {
        "campaign_name": "test3", "status": "player", "character_name": "Crash Bandicot"
    },
    {
        "campaign_name": "test1", "status": "player", "character_name": "Steve Rogers"
    },
    {
        "campaign_name": "test2", "status": "DM", "amout_of_players": "5"
    },
    {
        "campaign_name": "test3", "status": "player", "character_name": "Crash Bandicot"
    }
]
const campaigns2 = []

const campaigns = campaigns1

const campaignContainerSection = document.querySelector('.campaigns-container')
const noCampaignContainerSection = document.querySelector('.no-campaigns-container')
/* no campaigns */
if (campaigns.length === 0) {
    noSessions()
}
else {
    noCampaignContainerSection.style.display = 'none'
    campaigns.forEach(campaign => {
        if (campaign.status === "player") {
            displayPlayerSessions(campaign)
        }
        else if (campaign.status === "DM") {
            displayDMSessions(campaign)
        }
        else {
            console.log("NOT A PLAYER OR A DM!!!")
        }
    });
    addButtons(campaignContainerSection)
}

campaignContainerSection.addEventListener('click', (e) => {
    if (e.target.classList.contains('join-button')) {
        window.location.href = "./playerScreen.html"
    }
    else if (e.target.classList.contains('start-session-button')) {
        window.location.href = "./DMScreen.html"
    }
})

function addButtons() {
    const buttonsContainer = document.createElement('div')
    const createButton = document.createElement('button')
    const joinButton = document.createElement('button')
    buttonsContainer.classList.add("buttons-container")
    createButton.classList.add("create-button")
    let htmlCreate = `<dialog id="create-new-campaign-modal">
                <h3>Create a new campaign!</h3>
            <p>By creating the campaign, you will become the campaign DM</p>
            <input type="text" class="campaign-code" value="123123123" readonly>
            <button class="copy-button">Copy!</button>
            <p>Send the code above to your party so they can join the campaign</p>
            <p>The adventure awaits!</p>
            <button class="finish-create">Create Campaign!</button>
            <button type="button" id="cancel-create" class="cancel-button">
                Cancel
            </button>
            </dialog>`
    /* not to self the value="" should be value generated by backend */
    joinButton.classList.add("join-new-button")
    let htmlJoin = `<dialog id="join-new-campaign-modal">
              <form action="" class="join-new-campaign-form">
                <div class="capaign-code">
                  <h3>Enter the campaign code</h3>
                  <p>This should be provided by the DM</p>
                  <input type="text" name="campaign-code" id="campaign-code" placeholder="Campaign Code">
                </div>
                <div class="character-name">
                  <h3>Enter your Character's name</h3>
                  <input type="text" name="character-name" id="character-name" placeholder="Character's Name">
                </div>
                <div class="initial-submit">
                  <button type="submit" class="continue-join">Continue</button>
                  <!-- this is a submit on porpuse to give the dm time to approve while you create the character -->
                </div>
              </form>
              <form action="" class="character-info not-active">
                <input type="text" name="characters-class" id="characters-class" placeholder="Character's Class">
                <input type="text" name="characters-race" id="characters-race" placeholder="Character's Race">
                <div class="stats">
                  <input type="number" name="characters-str" id="characters-str" placeholder="Strength">
                  <input type="number" name="characters-dex" id="characters-dex" placeholder="Dexterity">
                  <input type="number" name="characters-con" id="characters-con" placeholder="Constitution">
                  <input type="number" name="characters-int" id="characters-int" placeholder="Inteligence">
                  <input type="number" name="characters-wis" id="characters-wis" placeholder="Wisdom">
                  <input type="number" name="characters-cha" id="characters-cha" placeholder="Charisma">
                </div>
                <div class="final-submit">
                  <button type="submit" class="finish-join">Join the Adventure</button>
                  <!-- add logic in back to actually add this -->
                </div>
              </form>
              <button type="button" id="cancel-join" class="cancel-button">
                Cancel
              </button>
            </dialog>`
    let completeHTML = htmlJoin + htmlCreate
    createButton.innerText = "Create Campaign"
    joinButton.innerText = "Join Campaign"
    buttonsContainer.appendChild(joinButton)
    buttonsContainer.appendChild(createButton)
    button_container.appendChild(buttonsContainer)
    buttonsContainer.innerHTML += completeHTML
}

function noSessions() {
    const noSessionsContainer = document.createElement('div')
    const messageContainer = document.createElement('div')
    const heading = document.createElement('h3')
    const message = document.createElement('p')

    noSessionsContainer.classList.add("no-session-container")
    messageContainer.classList.add("empty-state-message")
    heading.innerText = "You have no active campaigns"
    message.innerText = "It seems your adventure hasn't started yet\nJoin a party as a player or create new world as a DM!\nYour journey awaits!"

    messageContainer.appendChild(heading)
    messageContainer.appendChild(message)
    addButtons(messageContainer)
    noSessionsContainer.appendChild(messageContainer)

    campaignContainerSection.style.display = 'none'

    noCampaignContainerSection.appendChild(noSessionsContainer)
}

function displayDMSessions(campaign) {
    const campaignName = campaign.campaign_name
    const status = campaign.status
    const playerCount = campaign.amout_of_players

    const campaignInstance = document.createElement('div')
    const buttonsContainer = document.createElement('div')
    const campaignNameSpan = document.createElement('span')
    const statusSpan = document.createElement('span')
    const playerCountSpan = document.createElement('span')
    const startSessionButton = document.createElement('button')
    const abandonButton = document.createElement('button')

    campaignInstance.classList.add('campaign-instance', 'dm-campaign')
    buttonsContainer.classList.add("instance-buttons-container")
    startSessionButton.classList.add('start-session-button')
    abandonButton.classList.add('abandon-button')

    campaignNameSpan.innerText = `Campaign name: ${campaignName}`
    statusSpan.innerText = `Status: ${status}`
    playerCountSpan.innerText = `Amount of players: ${playerCount}`
    startSessionButton.innerText = "Host Session"
    abandonButton.innerText = "Abandon Campaign"

    campaignInstance.appendChild(campaignNameSpan)
    campaignInstance.appendChild(statusSpan)
    campaignInstance.appendChild(playerCountSpan)
    campaignInstance.appendChild(buttonsContainer)
    buttonsContainer.appendChild(startSessionButton)
    buttonsContainer.appendChild(abandonButton)

    campaignContainerSection.appendChild(campaignInstance)
}

function displayPlayerSessions(campaign) {
    const campaignName = campaign.campaign_name
    const status = campaign.status
    const characterName = campaign.character_name

    const campaignInstance = document.createElement('div')
    const buttonsContainer = document.createElement('div')
    const campaignNameSpan = document.createElement('span')
    const statusSpan = document.createElement('span')
    const nameSpan = document.createElement('span')
    const joinButton = document.createElement('button')
    const abandonButton = document.createElement('button')

    campaignInstance.classList.add('campaign-instance', 'player-campaign')
    buttonsContainer.classList.add("instance-buttons-container")
    joinButton.classList.add('join-button')
    abandonButton.classList.add('abandon-button')

    campaignNameSpan.innerText = `Campaign name: ${campaignName}`
    statusSpan.innerText = `Status: ${status}`
    nameSpan.innerText = `Character's name: ${characterName}`
    joinButton.innerText = "Join Session"
    abandonButton.innerText = "Abandon Campaign"

    campaignInstance.appendChild(campaignNameSpan)
    campaignInstance.appendChild(statusSpan)
    campaignInstance.appendChild(nameSpan)
    buttonsContainer.appendChild(joinButton)
    buttonsContainer.appendChild(abandonButton)
    campaignInstance.appendChild(buttonsContainer)

    campaignContainerSection.appendChild(campaignInstance)
}

const dmCampaigns = document.querySelectorAll('.dm-campaign')
const playerCampaigns = document.querySelectorAll('.player-campaign')

player_button.addEventListener('click', () => {

    if (player_button.classList.contains('not-clicked')) {
        if (dm_button.classList.contains('clicked')) {
            dm_button.classList.remove('clicked')
            dm_button.classList.add('not-clicked')
        }
        player_button.classList.remove('not-clicked')
        player_button.classList.add('clicked')

        dmCampaigns.forEach(campaign => campaign.style.display = 'none')
        playerCampaigns.forEach(campaign => campaign.style.display = '')
    }
    else {
        player_button.classList.remove('clicked')
        player_button.classList.add('not-clicked')
        dmCampaigns.forEach(campaign => campaign.style.display = '')
    }

    player_button.blur()            //will probably need to chage it later to what it takes to
})

dm_button.addEventListener('click', () => {

    if (dm_button.classList.contains('not-clicked')) {
        if (player_button.classList.contains('clicked')) {
            player_button.classList.remove('clicked')
            player_button.classList.add('not-clicked')
        }
        dm_button.classList.remove('not-clicked')
        dm_button.classList.add('clicked')

        playerCampaigns.forEach(campaign => campaign.style.display = 'none')
        dmCampaigns.forEach(campaign => campaign.style.display = '')
    }
    else {
        dm_button.classList.remove('clicked')
        dm_button.classList.add('not-clicked')
        playerCampaigns.forEach(campaign => campaign.style.display = '')
    }

    dm_button.blur()                //will probably need to chage it later to what it takes to
})

logo.addEventListener('click', () => {
    logo.blur()
})

log_out.addEventListener('click', () => {
    log_out_modal.showModal()
    cancel_logout_button.blur()
});

cancel_logout_button.addEventListener('click', () => {
    log_out_modal.close()
    log_out.blur()
})

confirm_logout_button.addEventListener('click', () => {
    /* some save to database logic that needs to come in the future */
    window.location.href = "index.html"
})

const join_new_campaign = document.getElementsByClassName("join-new-button")[0];
const join_new_campaign_modal = document.getElementById("join-new-campaign-modal");
const cancel_join_new_campaign = document.getElementById("cancel-join");
const continue_join = document.getElementsByClassName("continue-join")[0];
const join_form = document.getElementsByClassName("join-new-campaign-form")[0];
const character_info = document.getElementsByClassName("character-info")[0];
const create_new_campaign = document.getElementsByClassName("create-button")[0];
const create_new_campaign_modal = document.getElementById("create-new-campaign-modal");
const cancel_create_new_campaign = document.getElementById("cancel-create");
const copy_button = document.getElementsByClassName("copy-button")[0];
const code_value = document.getElementsByClassName("campaign-code")[0];
const finish_creating = document.getElementsByClassName("finish-create")[0];


join_new_campaign.addEventListener('click', () => {
    join_new_campaign_modal.showModal()
    cancel_join_new_campaign.blur()
})

cancel_join_new_campaign.addEventListener('click', () => {
    join_new_campaign_modal.close()
    join_new_campaign.blur()
})

join_form.addEventListener('submit', (e) => {
    e.preventDefault()
    // send message to dm to confirm the player can join
    continue_join.blur()
    join_form.classList.add("not-active")
    character_info.classList.remove("not-active")
})

create_new_campaign.addEventListener('click', () => {
    create_new_campaign_modal.showModal()
    cancel_create_new_campaign.blur()
})

cancel_create_new_campaign.addEventListener('click', () => {
    create_new_campaign_modal.close()
    create_new_campaign.blur()
})

copy_button.addEventListener('click', () => {
    const codeToCopy = code_value.value;
    navigator.clipboard.writeText(codeToCopy)
    .then(() => {
        copy_button.innerText = "Copied!"
        copy_button.classList.add("copied")
        setTimeout(() => {
            copy_button.innerText = "Copy!"
            copy_button.classList.remove("copied")
        }, 2000)
    })
    .catch(err => {
        console.error("Failed to copy code: ", err)
    })
})

finish_creating.addEventListener('click', () => {
    create_new_campaign_modal.close()
    create_new_campaign.blur()
    /* some backend logic to create the actual campaign, maybe load the page aswell */
})